name: Deploy CDK

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # ✅ Install Node.js for CDK CLI
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ✅ Install AWS CDK CLI globally
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy CDK
        run: |
          source .venv/bin/activate
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Deploying to PROD..."
            cdk deploy \
              -c env=prod \
              -c account=${{ secrets.AWS_ACCOUNT_PROD }} \
              -c region=${{ secrets.AWS_REGION_PROD }} \
              --require-approval never
          else
            echo "Deploying to DEV..."
            cdk deploy \
              -c env=dev \
              -c account=${{ secrets.AWS_ACCOUNT_DEV }} \
              -c region=${{ secrets.AWS_REGION_DEV }} \
              --require-approval never
          fi

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION_DEV: us-east-1
          AWS_ACCOUNT_DEV: ${{ secrets.AWS_ACCOUNT_DEV }}
          AWS_ACCOUNT_PROD: ${{ secrets.AWS_ACCOUNT_PROD }}

